Repository Health-Food-Me/Health-Food-Me-iOS, pull requests merged in 2022-07, with the labels that each got.

#7 [Chore] #6 - SwiftLint 적용 및 경고 수정작업
  HealthFoodMe/.swiftlint.yml
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/BaseRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/NetworkResult.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/AuthRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/HomeRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/AuthService.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/HomeService.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/GeneralResponse.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/Reactive+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/String+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UIImage+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UITabBar+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UITableView+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UITextField+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UITextView+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UIView+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UIViewController+.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UserDefaults+.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/BaseNotiList.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Protocols/UITableViewRegisterable.swift
  HealthFoodMe/HealthFoodMe/Global/Protocols/ViewModelType.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/Base/BaseVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Home/PostDetailScene/Cells/PostImageCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Home/PostDetailScene/VC/PostDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Home/PostDetailScene/Views/PostDetailBottomView.swift
  HealthFoodMe/HealthFoodMe/Utils/Adjusted+.swift
  HealthFoodMe/HealthFoodMe/Utils/ShowToast.swift
  HealthFoodMe/HealthFoodMe/Utils/buttonPress.swift
  HealthFoodMe/HealthFoodMe/Utils/calculatePastTime.swift
  HealthFoodMe/HealthFoodMe/Utils/makeAlert.swift
  HealthFoodMe/HealthFoodMe/Utils/makeVibrate.swift
  HealthFoodMe/HealthFoodMe/Utils/manageObserverAction.swift
  HealthFoodMe/HealthFoodMe/Utils/setDefaultFonts.swift
  HealthFoodMe/HealthFoodMe/Utils/setImage.swift
  HealthFoodMe/Podfile
  HealthFoodMe/Podfile.lock
Labels: 🧑🏻‍💻Duno, Chore

#10 [Fix] #9 - 프로필 설정
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
Labels: Fix, 🧑🏻‍💻Duno

#14 [Feat] 소셜로그인 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/AppDelegate.swift
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authSubTitle.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authSubTitle.imageset/authSubTitle.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authSubTitle.imageset/authSubTitle@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authSubTitle.imageset/authSubTitle@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authTitle.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authTitle.imageset/authTitle.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authTitle.imageset/authTitle@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/authTitle.imageset/authTitle@3x.png
  HealthFoodMe/HealthFoodMe/HealthFoodMe.entitlements
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLogin.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Home/PostDetailScene/Layout/PostDetailCVLayout.swift
  HealthFoodMe/HealthFoodMe/Presentation/Home/PostDetailScene/VC/PostDetailVC.swift
  HealthFoodMe/Podfile.lock
Labels: Feat, 🌈YunDol

#18 [Add] #15 - Color 추가
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Extension/Design/UIColor+.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeBgGray.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeBlack.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeGray1.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeGray2.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeInactiveGray.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeLineGray.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeTagGray.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeWhite.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/mainGreen.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/mainRed.colorset/Contents.json
Labels: Add, ☁️YoungIn

#21 [Design] #5-식당 상세 메뉴 UI구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UIView+.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick@3x.png
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Cells/MenuCellCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTab.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/ViewModel/MenuDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/HeaderView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/MenuDetailView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/MenuView.swift
Labels: Design, 🤖Lyn

#29 [Design] #26 - 앱 아이콘 설정
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Design, 🤖Lyn

#25 [Feat] #23 - StarRating 커스텀 컴포넌트 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star.imageset/icn_star.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star.imageset/icn_star@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star.imageset/icn_star@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_25.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_25.imageset/Group 267.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_25.imageset/Group 267@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_25.imageset/Group 267@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_50.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_50.imageset/Group 268.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_50.imageset/Group 268@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_50.imageset/Group 268@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_75.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_75.imageset/Group 269.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_75.imageset/Group 269@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_75.imageset/Group 269@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_filled.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_filled.imageset/icn_star_filled.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_filled.imageset/icn_star_filled@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Common/icn_star_filled.imageset/icn_star_filled@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/StarRatingView.swift
Labels: Feat, 🧑🏻‍💻Duno

#39 [Design] #8 - 지도 뷰 기본 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Map/MainMapScene/MainMapModel.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_magnifying.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_magnifying.imageset/Group.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_magnifying.imageset/Group@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_magnifying.imageset/Group@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_diet.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_diet.imageset/icn_mappin_diet.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_diet.imageset/icn_mappin_diet@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_diet.imageset/icn_mappin_diet@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_normal.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_normal.imageset/icn_mappin_normal.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_normal.imageset/icn_mappin_normal@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mappin_normal.imageset/icn_mappin_normal@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_menu.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_menu.imageset/Vector.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_menu.imageset/Vector@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_menu.imageset/Vector@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mylocation.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mylocation.imageset/Group 83.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mylocation.imageset/Group 83@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_mylocation.imageset/Group 83@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Cells/MenuCategoryCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Cells/TagCVCFlowLayout.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Cells/TagSummaryCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Views/MapDetailSummaryView.swift
Labels: Design, 🧑🏻‍💻Duno

#44 [Feat] #40 - 지도, 햄버거바, 상세페이지, 검색뷰 플로우 연결
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Cells/DetailTabTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#46 [Feat] #38 - Custom Segment Control 완성 + 컨플릭트 해결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/CustomSegementControl.swift
Labels: 👑PrinceSong

#48 [Design] #28 - 검색 완료 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UILabel+.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewmap.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewmap.imageset/Group 94.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewmap.imageset/Group 94@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewmap.imageset/Group 94@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/icn_x.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/icn_x.imageset/icn_x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/icn_x.imageset/icn_x@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/icn_x.imageset/icn_x@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchRecentTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchResultTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Protocol/SearchResultModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResult.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Design, ☁️YoungIn

#57 [Add] 추가 Color 세팅
  HealthFoodMe/HealthFoodMe/Global/Extension/Design/UIColor+.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeCardlineGray.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeGreenSubDark.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeGreenSubLight.colorset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Color.xcassets/helfmeRedSub.colorset/Contents.json
Labels: Add, 🌈YunDol

#50 [Design] #47 - 검색 empty UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/img_search.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/img_search.imageset/img_search.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/img_search.imageset/img_search@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/img_search.imageset/img_search@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Views/SearchEmptyView.swift
Labels: Design, ☁️YoungIn

#54 [Design] #43 - 상세페이지 블로그 리뷰 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/CustomSegementControl.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/Cells/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/Cells/ReviewHeaderCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/VC/BlogReviewTab.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/VC/BlogReviewTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/ViewModel/BlogReviewDataModel.swift
Labels: Design, 🌈YunDol

#59 [Chore] #58 - 소셜로그인 뷰 UI 수정
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
Labels: Chore, 🌈YunDol

#62 [Design] #55 - 스크랩북 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_bookmark_inactive.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_bookmark_inactive.imageset/btn_bookmark_inactive.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_bookmark_inactive.imageset/btn_bookmark_inactive@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_bookmark_inactive.imageset/btn_bookmark_inactive@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_scrap.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_scrap.imageset/btn_scrap.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_scrap.imageset/btn_scrap@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/btn_scrap.imageset/btn_scrap@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icn_bookmark.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icn_bookmark.imageset/icn_bookmark.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icn_bookmark.imageset/icn_bookmark@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icn_bookmark.imageset/icn_bookmark@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icon_before.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icon_before.imageset/icon_before.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icon_before.imageset/icon_before@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/icon_before.imageset/icon_before@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/tempBurger.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/tempBurger.imageset/Group 310.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/tempBurger.imageset/Group 310@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Scrap/tempBurger.imageset/Group 310@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Model/ScrapDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/Scrap.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/View/ScrapEmptyView.swift
Labels: Design, ☁️Jenny

#65 [Design] #22-리뷰 작성 UI
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/btn_delete.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/btn_delete.imageset/btn_imgdelete.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/btn_delete.imageset/btn_imgdelete@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/btn_delete.imageset/btn_imgdelete@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/icn_photoAdd.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/icn_photoAdd.imageset/Vector.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/icn_photoAdd.imageset/Vector@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewWrite/icn_photoAdd.imageset/Vector@3x.png
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/Cells/AddPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/Cells/ListPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWrite.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/ViewModel/PhotoDataModel.swift
  HealthFoodMe/Podfile
  HealthFoodMe/Podfile.lock
Labels: Feat, 🤖Lyn

#61 [Feat] #20 - 상세페이지 URLScheme 기능 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/URLSchemeManager.swift
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Detail/MainDetailScene/MainDetailModel.swift
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Cells/ExpandableInfoTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Cells/MainInfoTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Utils/EncodeURLKorean.swift
Labels: Feat, 🧑🏻‍💻Duno

#64 [Feat] #60 - 상세페이지 화면전환 및 팬제스쳐 기능 구현
  HealthFoodMe/HealthFoodMe/Domain/Model/Map/MainMapScene/MainMapModel.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_bossam.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_bossam.imageset/icn_bossam.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_bossam.imageset/icn_bossam@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_bossam.imageset/icn_bossam@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_dupbap.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_dupbap.imageset/icn_dupbap.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_dupbap.imageset/icn_dupbap@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_dupbap.imageset/icn_dupbap@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_kimbap.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_kimbap.imageset/icn_kimbap.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_kimbap.imageset/icn_kimbap@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_kimbap.imageset/icn_kimbap@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_meat.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_meat.imageset/icn_meat.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_meat.imageset/icn_meat@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_meat.imageset/icn_meat@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_poke.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_poke.imageset/icn_poke.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_poke.imageset/icn_poke@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_poke.imageset/icn_poke@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_salad.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_salad.imageset/icn_salad.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_salad.imageset/icn_salad@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_salad.imageset/icn_salad@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_sandwich.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_sandwich.imageset/icn_sandwich.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_sandwich.imageset/icn_sandwich@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_sandwich.imageset/icn_sandwich@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_shabushabu.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_shabushabu.imageset/icn_shabushabu.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_shabushabu.imageset/icn_shabushabu@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Map/icn_shabushabu.imageset/icn_shabushabu@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Cells/DetailTabTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Cells/MenuCategoryCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#63 [Feat] 닉네임 수정 뷰 완성
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Author/ChangeNicknameScene/ChangeNicknameEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Repository/Auth/ChangeNicknameScene/NicknameChangeRepository.swift
  HealthFoodMe/HealthFoodMe/Domain/Usecase/Auth/NicknameChangeScene/NicknameChangeUseCase.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/NicknameChangeScene/VC/NicknameChangeVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/NicknameChangeScene/ViewModel/NicknameChangeViewModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/NicknameChangeScene/Views/NicknameChange.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/CTAButton.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/UpperToastView.swift
  HealthFoodMe/HealthFoodMe/Utils/addTextFieldPadding.swift
Labels: Add, P2 / Priority Middle

#76 [Feat] #68 - CustomAlert창 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UIViewController+.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelpmeAlerts/VC/HelfmeAlert.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelpmeAlerts/VC/HelfmeAlertVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelpmeAlerts/Views/LogoutAlertView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelpmeAlerts/Views/ReviewDeleteAlertView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelpmeAlerts/Views/WithdrawalAlertView.swift
Labels: Feat, ☁️Jenny

#72 [Design] #67-리뷰 작성 UI 디테일적인 부분 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Utils/addToolBar.swift
Labels: Design, 🤖Lyn

#81 [Feat] #53 - 검색 관련 로직 정리
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_search_delete.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_search_delete.imageset/btn_delete.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_search_delete.imageset/btn_delete@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_search_delete.imageset/btn_delete@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchResultTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Protocol/SearchResultModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Feat, ☁️Jenny

#84 [Design] #36 - 상세페이지 리뷰 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Application/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/VC/BlogReviewTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/ReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/ReviewHeaderCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/ReviewPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/TagCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetail.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/ViewModel/BlogReviewDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/ViewModel/ReviewDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Views/CustomTagLabel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Views/CustomTagLabelVC.swift
Labels: Design, 🌈YunDol

#89 [Design] #82 - 검색 레이아웃 설정
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Design, ☁️Jenny

#86 [Design] #85-상세 메뉴 UI 수정
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/Image.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/Image.imageset/Image.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/Image.imageset/Image@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/Image.imageset/Image@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/icn_pick.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/icn_pick.imageset/icn_pick.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/icn_pick.imageset/icn_pick@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/icn_pick.imageset/icn_pick@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/img_empty_card.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/img_empty_card.imageset/img_empty_card.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/img_empty_card.imageset/img_empty_card@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/MenuTab/img_empty_card.imageset/img_empty_card@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Cells/MenuCellCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/ViewModel/MenuDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/HeaderView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/MenuView.swift
Labels: Design, 🤖Lyn

#83 [Design] 외식대처법 UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_green.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_green.imageset/icn_tip_check_green.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_green.imageset/icn_tip_check_green@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_green.imageset/icn_tip_check_green@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_pink.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_pink.imageset/icn_tip_check_pink.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_pink.imageset/icn_tip_check_pink@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/icn_tip_check_pink.imageset/icn_tip_check_pink@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_Tasteit.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_Tasteit.imageset/img_tip_Tasteit.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_Tasteit.imageset/img_tip_Tasteit@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_Tasteit.imageset/img_tip_Tasteit@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_empty.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_empty.imageset/img_tip_empty.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_empty.imageset/img_tip_empty@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_empty.imageset/img_tip_empty@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_recommend.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_recommend.imageset/img_tip_recommend.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_recommend.imageset/img_tip_recommend@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/CopingTab/img_tip_recommend.imageset/img_tip_recommend@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Image.imageset/Image@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_delete.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_delete.imageset/btn_delete.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_delete.imageset/btn_delete@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_delete.imageset/btn_delete@3x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/icn_pick.imageset/icn_pick@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/Cells/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/Cells/ReviewHeaderCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/VC/BlogReviewTab.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/VC/BlogReviewTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/BlogReviewTabScene/ViewModel/BlogReviewDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/Cell/ContentTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/VC/CopingTab.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/VC/CopingTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/ViewModel/CopingDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/Views/CopingEmptyView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/Views/CopingHeaderView.swift
Labels: Design, 🤖Lyn

#92 [Design] #87 - 리뷰 탭 Empty View UI 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewDetail/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewDetail/img_review_empty.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewDetail/img_review_empty.imageset/img_review_empty.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewDetail/img_review_empty.imageset/img_review_empty@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/ReviewDetail/img_review_empty.imageset/img_review_empty@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/ReviewEmptyViewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/ViewModel/BlogReviewDataModel.swift
Labels: Design, 🌈YunDol

#97 [Chore] #90 - 검색 및 스크랩 디테일 수정
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/View/ScrapEmptyView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
Labels: Chore, ☁️Jenny

#95 [Design] 메뉴 부분 UI 재작업
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Cells/MenuCellCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/ViewModel/MenuDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Views/MenuView.swift
Labels: Design, 🤖Lyn

#99 [Design] 리뷰 작성 UI 변경사항 작업
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/Cells/AddPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
Labels: Design, 🤖Lyn

#101 [Design] #100-스플래시 화면 UI
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StoryboardLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/Splash.storyboard
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/SplashVC.swift
  HealthFoodMe/Podfile
  HealthFoodMe/Podfile.lock
Labels: Design, 🤖Lyn

#105 [Merge] #93 - 상세페이지 리뷰 탭 더보기 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/BlogReview/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Common/ReviewEmptyViewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Common/ReviewHeaderCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/TagCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Feat, 🌈YunDol

#107 [Feat] #106 - URL Scheme 기능 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/URLSchemeManager.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/ViewModel/BlogReviewDataModel.swift
Labels: Feat, 🌈YunDol

#108 [Feat] #98 - 햄버거바 플로우 연결 및 제보하기 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
Labels: Feat, ☁️Jenny

#111 [Fix] #110 - 블로그 url scheme 분기처리 오류 수정
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Fix, 🌈YunDol

#117 [Fix] #114 - 서버통신 로직 수정 및 UserManager 클래스 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/UserManager.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/BaseRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/HeaderType.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/RestaurantRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/AuthService.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/RestaurantService.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Map/MainMapScene/RestaurantSummaryModel.swift
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Utils/UserDefaultWrapper.swift
Labels: Feat, Fix, 🧑🏻‍💻Duno

#119 [Feat] 외식대처법 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/CopingTabScene/CopingTabEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/HeaderType.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/RestaurantRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/RestaurantService.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/Cell/ContentTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/VC/CopingTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/ViewModel/CopingDataModel.swift
Labels: Feat, 🤖Lyn

#123 [Feat] #115 - 소셜 로그인 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/UserManager.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Author/SocialLoginScene/SocialLoginEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/AuthRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/AuthService.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
Labels: Feat, 🌈YunDol

#126 [Fix] #113 - 검색 관련 이슈 수정
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Chore, ☁️Jenny

#125 [Feat] #118 - FiebaseCrashlytics 및 FirebaseAnalytics 연동
  .gitignore
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe.xcodeproj/xcshareddata/xcschemes/HealthFoodMe.xcscheme
  HealthFoodMe/HealthFoodMe/Application/AppDelegate.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/AnalyticsType.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/AppLog.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/EventType/LogEventType.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/FirebaseConfigureServiceProtocol.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/Provider/FirebaseAnalyticsProvider.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/Analytics/Provider/RuntimeProviderType.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/URLScheme/URLSchemeManager.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/User/UserManager.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Base/SceneDelegate.swift
Labels: Feat, 🧑🏻‍💻Duno

#130 [Feat] #128 - 소셜로그인 자동로그인 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/AppDelegate.swift
  HealthFoodMe/HealthFoodMe/Application/Manager/User/UserManager.swift
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Base/SceneDelegate.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Author/Reissuance/Reissuance.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Author/SocialLoginScene/SocialLoginEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/BaseRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/HeaderType.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/AuthRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/AuthService.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/SplashVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#131 [Feat] #124 - 리뷰 리스트 조회 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/ReviewTabScene/ReviewListEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/HeaderType.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/ReviewRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/ReviewService.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/ViewModel/ReviewDataModel.swift
Labels: Feat, 🌈YunDol

#127 [Feat] #116 - 스크랩 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Data/Entity/User/ScrapScene/ScrapEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/User/ScrapScene/ScrapListEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/UserRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/UserService.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Model/ScrapDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
Labels: Feat, ☁️Jenny

#136 [Fix] #135 - 리뷰 리스트 API 수정 사항 반영
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/ReviewTabScene/ReviewListEntity.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
Labels: Fix, 🌈YunDol

#134 [Add] #132 - 회원탈퇴 API 기초 파일 생성
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Data/Entity/Author/withdrawalScene/withdrawalEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/AuthRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/AuthService.swift
Labels: Feat, 🌈YunDol

#137 [Feat] #129 - 검색 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Data/Entity/Search/SearchEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Search/SearchRequestEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Search/SearchResultEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/RestaurantRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/RestaurantService.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Search/SearchDataModel.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Search/SearchResultDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Protocol/SearchResultModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Feat, ☁️Jenny

#141 [Fix] #140 - 리뷰탭 QA 반영
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Fix, 🌈YunDol

#148 [Feat] #142 - 블로그 리뷰 리스트 조회 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/URLScheme/URLSchemeManager.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/ReviewTabScene/BlogReviewListEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/ReviewRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/ReviewService.swift
  HealthFoodMe/HealthFoodMe/Global/Extension/UI/UILabel+.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/BlogReview/BlogReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Feat, 🌈YunDol

#153 [Fix] #138 - 검색 디테일 수정
  HealthFoodMe/HealthFoodMe/Data/Entity/Search/SearchRequestEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Search/SearchResultEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/RestaurantRouter.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Search/SearchResultDataModel.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/ImageLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewlist.imageset/Contents.json
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewlist.imageset/Group 352.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewlist.imageset/Group 352@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Search/btn_viewlist.imageset/Group 352@3x.png
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchResultTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Fix, ☁️Jenny

#158 [Fix] #154 - 스크랩북 디테일 수정
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
Labels: Fix, ☁️Jenny

#160 [Feat] #147-리뷰 삭제 API 연결
  HealthFoodMe/GoogleService-Info.plist
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Data/Entity/Map/MyReviewScene/MyReviewEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Map/MyReviewScene/ReviewDeleteEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Foundation/HeaderType.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/ReviewRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/ReviewService.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Map/MyReviewScene/MyReviewModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/Cells/MyReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/VC/MyReviewVC.swift
Labels: Feat, 🤖Lyn

#164 [Chore] 외식대처법UI 디테일 수정, 외식 대처법, 리뷰탭 API 연결
  HealthFoodMe/GoogleService-Info.plist
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/Cell/ContentTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/VC/CopingTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Chore, 🤖Lyn

#175 [Feat] #169 - 카테고리 선택 기능 구현
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Views/mapContainerView + Reactive.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Views/mapContainerView.swift
Labels: Feat, 🧑🏻‍💻Duno

#173 [Feat] #172 - 사진 확대 기능 추가
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Global/Literals/BaseNotiList.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/Review/ReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Utils/ImageForSlide.swift
  HealthFoodMe/Podfile
  HealthFoodMe/Podfile.lock
Labels: Feat, 🌈YunDol

#181 [Chore] #177 - 기기별 레이아웃 확인
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/SplashVC.swift
Labels: Chore, 🌈YunDol

#178 [Fix] #176 - 검색 및 스크랩 KingFisher 적용
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/Cells/SearchResultTVC.swift
Labels: Fix, ☁️Jenny

#180 [Feat] #179 - 검색 결과 거리순 정렬
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Feat, ☁️Jenny

#183 [Feat] #170 - 지도 및 스크랩 뷰 보조 지도 기능 구현
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/MainDetailScene/MainDetailEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/User/ScrapScene/ScrapListEntity.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Views/DetailSummaryView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/SupplementMapScene/VC/SupplementMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#185 [Feat] 리뷰 수정 API 연결
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/ModuleFactory/Factory/ModuleFactory.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Map/MyReviewScene/MyReviewEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Map/MyReviewScene/ReviewEditEntity.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/ReviewRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Services/ReviewService.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Map/MyReviewScene/MyReviewModel.swift
  HealthFoodMe/HealthFoodMe/Global/Literals/StringLiterals.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/StarRatingSlider.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/Cells/ListPhotoCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/Cells/MyReviewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/Cells/MyReviewEmptyViewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/VC/MyReviewVC.swift
Labels: Feat, 🤖Lyn

#188 [Chore] #187 - 리뷰 편집 이미지 뜨게 수정
  HealthFoodMe/HealthFoodMe/Presentation/Common/HelfmeLoading/View/HelfmeLoadingView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
Labels: Chore, ☁️Jenny

#196 [Feat] #186-내가 쓴 리뷰에서 식당 클릭 시 식당 상세로 이동
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/Cells/MyReviewCVC.swift
Labels: Feat, 🤖Lyn

#191 [Fix] #190 - 햄버거바 2차 QA 적용
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Setting/VC/SettingVC.swift
Labels: Fix, 🌈YunDol

#197 [Fix] #194 - emptyView 레이아웃 수정
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/Cells/MyReviewEmptyViewCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/VC/MyReviewVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/View/ScrapEmptyView.swift
Labels: Fix, ☁️Jenny

#198 [Fix] #192 - 리뷰 탭 QA 반영
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Fix, 🌈YunDol

#199 [Feat] #184 - 릴리즈 심사 전 잡일
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/User/UserManager.swift
  HealthFoodMe/HealthFoodMe/Data/Network/Routers/ReviewRouter.swift
  HealthFoodMe/HealthFoodMe/Data/Repository/Auth/ChangeNicknameScene/NicknameRepository.swift
  HealthFoodMe/HealthFoodMe/Domain/Model/Detail/MainDetailScene/MainDetailModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/UserWithdrawlScene/VC/UserWithdrawalVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Cells/ExpandableInfoTVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/Views/DetailSummaryView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/VC/MenuTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Views/MapDetailSummaryView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MyReviewScene/VC/MyReviewVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/SupplementMapScene/VC/SupplementMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/VC/ScrapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/SplashVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#200 [Fix] 외식대처법, 리뷰 작성 QA 반영
  HealthFoodMe/HealthFoodMe/Presentation/Detail/CopingTabScene/VC/CopingTabVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
  HealthFoodMe/HealthFoodMe/Utils/addToolBar.swift
Labels: Fix, 🤖Lyn

#206 [Fix] #201 - 리뷰 alert창 오타 수정
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewWriteScene/VC/ReviewWriteVC.swift
Labels: Fix, ☁️Jenny

#208 [Fix] #207 - 블로그 리뷰 컨텐츠 길이 수정
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/Cells/BlogReview/BlogReviewCVC.swift
Labels: Fix, 🌈YunDol

#209 [Fix] A순위 QA반영
  HealthFoodMe/HealthFoodMe/Presentation/Auth/NicknameChangeScene/VC/NicknameChangeVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/UserWithdrawlScene/VC/UserWithdrawalVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Common/UI Components/CustomSegementControl.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Setting/VC/SettingVC.swift
Labels: Fix, 🤖Lyn

#212 [Fix] #211 - 검색 관련 수정사항
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchVC.swift
Labels: Fix, ☁️Jenny

#214 [Feat] #205, #210 - 리젝 관련 사유 수정 및 검색 기능 수정
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Application/Manager/URLScheme/URLSchemeManager.swift
  HealthFoodMe/HealthFoodMe/Data/Entity/Detail/MainDetailScene/MainDetailEntity.swift
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/btn_login_apple.imageset/btn_login_apple.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/btn_login_apple.imageset/btn_login_apple@2x.png
  HealthFoodMe/HealthFoodMe/Global/Resources/Assets.xcassets/Auth/btn_login_apple.imageset/btn_login_apple@3x.png
  HealthFoodMe/HealthFoodMe/Info.plist
  HealthFoodMe/HealthFoodMe/Presentation/Auth/SocialLoginScene/VC/SocialLoginVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Auth/UserWithdrawlScene/VC/UserWithdrawalVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MainDetailScene/VC/MainDetailVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/Cells/MenuCellCVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Detail/MenuTabScene/ViewModel/MenuDataModel.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/HamburgerBarScene/HamburgerBarVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapNavigationController.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/VC/MainMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/MainMapScene/Views/mapContainerView.swift
  HealthFoodMe/HealthFoodMe/Presentation/Map/SupplementMapScene/VC/SupplementMapVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Search/SearchScene/VC/SearchResultVC.swift
  HealthFoodMe/HealthFoodMe/Presentation/Splash/SplashScene/VC/SplashVC.swift
Labels: Feat, 🧑🏻‍💻Duno

#216 [Fix] #215 - 스크랩 관련 디테일 수정
  HealthFoodMe/HealthFoodMe.xcodeproj/project.pbxproj
  HealthFoodMe/HealthFoodMe/Presentation/Scrap/ScrapScene/Cells/ScrapCVC.swift
Labels: Fix, ☁️Jenny

#218 [Fix] #217 - 블로그 리뷰 셀 크기 변경
  HealthFoodMe/HealthFoodMe/Presentation/Detail/ReviewTabScene/VC/ReviewDetailVC.swift
Labels: Fix, 🌈YunDol
